#! /bin/bash

python initialization.py

python classify.py "iris" "1" "0"
python classify.py "breast" "1" "0"
python classify.py "horse_colic" "1" "0"
python classify.py "Gametes_Epistasis" "1" "0"
python classify.py "magic" "1" "0"
python classify.py "hypothyroid" "1" "0"
python classify.py "GSE2109_Breast" "1" "0"
python classify.py "GSE2109_BreastPathological_ER" "1" "0"
python classify.py "GSE2109_BreastPathological_HER2_Neu" "1" "0"
python classify.py "GSE2109_BreastHistology" "1" "0"
python classify.py "GSE2109_ColonPathological_M" "0" "1"
python classify.py "GSE2109_ColonHistology" "0" "1"
python classify.py "GSE2109_ColonFamily_History_of_Cancer" "0" "1"

python autosklearnClassify.py "iris" "1" "0" "Five Minutes"
python autosklearnClassify.py "breast" "1" "0" "Five Minutes"
python autosklearnClassify.py "horse_colic" "1" "0" "Five Minutes"
python autosklearnClassify.py "Gametes_Epistasis" "1" "0" "Five Minutes"
python autosklearnClassify.py "magic" "1" "0" "Five Minutes"
python autosklearnClassify.py "hypothyroid" "1" "0" "Five Minutes"
python autoskelarnClassify.py "GSE2109_BreastPathological_ER" "1" "0" "Five Minutes"
python autosklearnClassify.py "GSE2109_BreastPathological_HER2_Neu" "1" "0" "Five Minutes"
python autosklearnClassify.py "GSE2109_BreastHistology" "1" "0" "Five Minutes"
python autosklearnClassify.py "GSE2109_ColonPathological_M" "0" "1" "Five Minutes"
python autosklearnClassify.py "GSE2109_ColonHistology" "0" "1" "Five Minutes"
python autosklearnClassify.py "GSE2109_ColonFamily_History_of_Cancer" "0" "1" "Five Minutes"

python autosklearnClassify.py "iris" "1" "0" "One Hour"
python autosklearnClassify.py "breast" "1" "0" "One Hour"
python autosklearnClassify.py "horse_colic" "1" "0" "one Hour"
python autosklearnClassify.py "Gametes_Epistasis" "1" "0" "One Hour"
python autosklearnClassify.py "magic" "1" "0" "One Hour"
python autosklearnClassify.py "hypothyroid" "1" "0" "One Hour"
python autoskelarnClassify.py "GSE2109_BreastPathological_ER" "1" "0" "One Hour"
python autosklearnClassify.py "GSE2109_BreastPathological_HER2_Neu" "1" "0" "One Hour"
python autosklearnClassify.py "GSE2109_BreastHistology" "1" "0" "One Hour"
python autosklearnClassify.py "GSE2109_ColonPathological_M" "0" "1" "One Hour"
python autosklearnClassify.py "GSE2109_ColonHistology" "0" "1" "One Hour"
python autosklearnClassify.py "GSE2109_ColonFamily_History_of_Cancer" "0" "1" "One Hour"

python autosklearnClassify.py "iris" "1" "0" "Six Hours"
python autosklearnClassify.py "breast" "1" "0" "Six Hours"
python autosklearnClassify.py "horse_colic" "1" "0" "Six Hours"
python autosklearnClassify.py "Gametes_Epistasis" "1" "0" "Six Hours"
python autosklearnClassify.py "magic" "1" "0" "Six Hours"
python autosklearnClassify.py "hypothyroid" "1" "0" "Six Hours"
python autoskelarnClassify.py "GSE2109_BreastPathological_ER" "1" "0" "Six Hours"
python autosklearnClassify.py "GSE2109_BreastPathological_HER2_Neu" "1" "0" "Six Hours"
python autosklearnClassify.py "GSE2109_BreastHistology" "1" "0" "Six Hours"
python autosklearnClassify.py "GSE2109_ColonPathological_M" "0" "1" "Six Hours"
python autosklearnClassify.py "GSE2109_ColonHistology" "0" "1" "Six Hours"
python autosklearnClassify.py "GSE2109_ColonFamily_History_of_Cancer" "0" "1" "Six Hours"

python autosklearnClassify.py "iris" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "breast" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "horse_colic" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "Gametes_Epistasis" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "magic" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "hypothyroid" "1" "0" "Twenty Four Hours"
python autoskelarnClassify.py "GSE2109_BreastPathological_ER" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "GSE2109_BreastPathological_HER2_Neu" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "GSE2109_BreastHistology" "1" "0" "Twenty Four Hours"
python autosklearnClassify.py "GSE2109_ColonPathological_M" "0" "1" "Twenty Four Hours"
python autosklearnClassify.py "GSE2109_ColonHistology" "0" "1" "Twenty Four Hours"
python autosklearnClassify.py "GSE2109_ColonFamily_History_of_Cancer" "0" "1" "Twenty Four Hours"

python ensemblePredictions.py "1" "0" #run this line of code with new version of ensemblePredictions.py

python metrics.py  #run this line of code with new version of metrics.py 
